able to run the repo examples

diff --git a/vxbank-api/mx-simulator/Makefile b/vxbank-api/mx-simulator/Makefile
--- a/vxbank-api/mx-simulator/Makefile
+++ b/vxbank-api/mx-simulator/Makefile
@@ -22,22 +22,27 @@ docker-run:
 	docker run -d --name ${CONTAINER_NAME} ${CHAIN_SIMULATOR_IMAGE_NAME}:${CHAIN_SIMULATOR_IMAGE_TAG}
 
 docker-stop:
-	docker stop ${CONTAINER_NAME}
+	docker stop ${CONTAINER_NAME} || true
 
 docker-rm:
-	docker rm ${CONTAINER_NAME}
+	docker rm ${CONTAINER_NAME} || true
 
 setup-env:
 	rm -rf ${REPO_TEMP_DIR}
 	git clone --branch ${SIMULATOR_REPO_BRANCH} ${SIMULATOR_REPO_URL} ${REPO_TEMP_DIR}
 	python3 -m venv ${PIP_ENV_DIR}
 	. ${PIP_ENV_DIR}/bin/activate && pip install -r ${REPO_TEMP_DIR}/examples/requirements.txt
-	rm -rf ${REPO_TEMP_DIR}
 
-run-examples: setup-env
+run-repo-examples: setup-env
 	$(MAKE) docker-build
+	docker stop "${IMAGE_NAME}" || true
+	docker rm "${IMAGE_NAME}" || true
 	docker run -d --name "${IMAGE_NAME}" -p 8085:8085 ${CHAIN_SIMULATOR_IMAGE_NAME}:${CHAIN_SIMULATOR_IMAGE_TAG}
 	echo "Running script in ${REPO_TEMP_DIR}/scripts/run-examples"
-	. ${PIP_ENV_DIR}/bin/activate && /bin/bash ${REPO_TEMP_DIR}/scripts/run-examples/script.sh
+	if [ -f ${REPO_TEMP_DIR}/scripts/run-examples/script.sh ]; then \
+		cd ${REPO_TEMP_DIR}/scripts/run-examples && . ${PIP_ENV_DIR}/bin/activate && /bin/bash script.sh; \
+	else \
+		echo "script.sh not found in ${REPO_TEMP_DIR}/scripts/run-examples"; \
+	fi
 	docker stop "${IMAGE_NAME}"
 	docker rm ${IMAGE_NAME}
